const BASE_URL = "https://deepswe.datacurve.ai/artifacts";

const ARTIFACTS = [
  "summary",
  "leaderboard",
  "comparison",
  "analysis",
  "critiques",
  "corpus-stats",
  "repositories",
  "verification-behavior",
  "tasks",
] as const;

type Artifact = (typeof ARTIFACTS)[number];
type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };
type JsonObject = { [key: string]: JsonValue };

const RAW_DIR = "data/raw";
const REPORT_PATH = "data/README.md";
const MAIN_README_PATH = "README.md";
const OMIT_MERMAID = process.env.OMIT_MERMAID === "1";
const IGNORED_TOP_LEVEL_KEYS = new Set([
  "scope",
  "unit",
  "description",
  "generated_at",
  "selection_source",
  "deep_swe_source",
  "swebenchpro_source",
]);

async function main() {
  await Bun.$`mkdir -p ${RAW_DIR}`;

  const artifacts = new Map<string, JsonObject>();

  for (const artifact of ARTIFACTS) {
    const url = `${BASE_URL}/${artifact}.json`;
    const response = await fetch(url, {
      headers: { accept: "application/json" },
    });

    if (!response.ok) {
      throw new Error(`Failed to fetch ${url}: ${response.status} ${response.statusText}`);
    }

    const data = normalizeArtifact(artifact, (await response.json()) as JsonObject);
    artifacts.set(artifact, data);
    await Bun.write(`${RAW_DIR}/${artifact}.json`, `${stableStringify(data)}\n`);
  }

  await Bun.write(REPORT_PATH, renderReport(artifacts));
  await Bun.write(MAIN_README_PATH, renderMainReadme(artifacts));
}

function stableStringify(value: JsonValue): string {
  return JSON.stringify(sortJson(value), null, 2);
}

function normalizeArtifact(artifact: Artifact, data: JsonObject): JsonObject {
  const normalized = Object.fromEntries(
    Object.entries(data).filter(([key]) => !IGNORED_TOP_LEVEL_KEYS.has(key)),
  ) as JsonObject;

  if (artifact === "comparison") {
    normalized.rows = getRows(normalized).map((row) => omitKeys(row, ["swebenchpro_source_url"]));
  }

  if (artifact === "leaderboard") {
    normalized.rows = getRows(normalized).map((row) => omitKeys(row, ["ci_method", "selection_notes"]));
  }

  if (artifact === "repositories") {
    normalized.repositories = getRows(normalized, "repositories").map((row) => omitKeys(row, ["description", "stars"]));
  }

  return normalized;
}

function omitKeys(row: Row, keys: string[]): JsonObject {
  return Object.fromEntries(Object.entries(row).filter(([key, value]) => !keys.includes(key) && value !== undefined)) as JsonObject;
}

function sortJson(value: JsonValue): JsonValue {
  if (Array.isArray(value)) {
    return value.map(sortJson);
  }

  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value)
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([key, nested]) => [key, sortJson(nested)]),
    );
  }

  return value;
}

function renderReport(artifacts: Map<string, JsonObject>): string {
  const summary = getArtifact(artifacts, "summary");
  const leaderboard = getRows(getArtifact(artifacts, "leaderboard"));
  const comparison = getRows(getArtifact(artifacts, "comparison"));
  const analysis = getRows(getArtifact(artifacts, "analysis"));
  const critiques = getArtifact(artifacts, "critiques");
  const corpusStats = getArtifact(artifacts, "corpus-stats");
  const repositories = getArtifact(artifacts, "repositories");
  const verification = getRows(getArtifact(artifacts, "verification-behavior"));
  const tasks = getArtifact(artifacts, "tasks");

  return [
    "# DeepSWE published benchmark snapshot",
    "",
    "This directory is generated by `bun run scrape` from the public DeepSWE artifact JSON endpoints.",
    "The scraper writes stable JSON snapshots in `data/raw/` and this compact report so normal git diffs show upstream benchmark changes.",
    "Descriptive metadata and other noisy non-result fields are intentionally omitted before writing files.",
    "",
    "## Original source",
    "",
    "DeepSWE is published by DataCurve at [deepswe.datacurve.ai](https://deepswe.datacurve.ai). Please visit the original site for the canonical benchmark presentation and context.",
    "",
    `Artifact JSON source: ${BASE_URL}`,
    "",
    "## Summary",
    "",
    renderKeyValueTable(summary.counts && typeof summary.counts === "object" && !Array.isArray(summary.counts) ? summary.counts : {}),
    "",
    "## Leaderboard",
    "",
    renderTable(leaderboard, [
      ["model", "Model"],
      ["config", "Config"],
      ["pass_at_1", "pass@1", formatPercent],
      ["pass_at_4", "pass@4", formatPercent],
      ["n_passed", "Passed"],
      ["n_attempted", "Attempts"],
      ["n_tasks_attempted", "Tasks"],
      ["median_cost_usd", "Median cost", formatUsd],
      ["median_steps", "Median steps"],
    ]),
    "",
    "## DeepSWE vs SWE-Bench Pro",
    "",
    renderTable(comparison, [
      ["model", "Model"],
      ["deep_swe_pass_rate", "DeepSWE", formatPercent],
      ["swebenchpro_pass_rate", "SWE-Bench Pro", formatPercent],
    ]),
    "",
    "## Per-model behavior aggregates",
    "",
    renderTable(analysis, [
      ["model", "Model"],
      ["config", "Config"],
      ["pass_rate", "Pass rate", formatPercent],
      ["n_passed", "Passed"],
      ["n_tasks_attempted", "Tasks"],
      ["n_trials", "Trials"],
      ["median_duration_seconds", "Median duration", formatSeconds],
      ["median_agent_steps", "Median steps"],
      ["critique_bad_rate", "Critique bad rate", formatPercent],
    ]),
    "",
    "## Verification behavior",
    "",
    renderTable(verification, [
      ["model", "Model"],
      ["source", "Source"],
      ["n", "Trials"],
      ["authored_new_tests", "Authored tests"],
      ["ran_preexisting_suite", "Ran suite"],
      ["repro_script_only", "Repro only"],
      ["nothing", "Nothing"],
      ["unknown", "Unknown"],
    ]),
    "",
    "## Critiques",
    "",
    renderCritiques(critiques),
    "",
    "## Corpus stats",
    "",
    renderCorpusStats(corpusStats),
    "",
    "## Repository and task coverage",
    "",
    renderKeyValueTable({
      tasks: tasks.n_tasks ?? getRows(tasks).length,
      repositories: repositories.n_repositories ?? null,
    }),
    "",
    "Top repositories by task count:",
    "",
    renderTable(getRows(repositories, "repositories").slice(0, 20), [
      ["name", "Repository"],
      ["primary_language", "Language"],
      ["n_tasks", "Tasks"],
      ["n_files", "Files"],
    ]),
    "",
  ].join("\n");
}

function renderMainReadme(artifacts: Map<string, JsonObject>): string {
  const leaderboard = getRows(getArtifact(artifacts, "leaderboard"));

  return [
    "# DeepSWE changelog",
    "",
    "This repository tracks changes to the published DeepSWE benchmark results.",
    "",
    "> **Original source:** DeepSWE is published by DataCurve at [deepswe.datacurve.ai](https://deepswe.datacurve.ai). Please visit the original site for the canonical benchmark presentation and context.",
    "",
    "A scheduled GitHub workflow runs `bun run scrape`, normalizes the public artifact JSON, and commits only when result data changes.",
    "",
    ...(OMIT_MERMAID ? [
      "_Generated Mermaid charts are temporarily omitted because chart validation failed in the scheduled workflow._",
      "",
    ] : [
    "## Charts",
    "",
    "### DeepSWE score vs average cost",
    "",
    renderEfficiencyChart(leaderboard),
    "",
    "### pass@1 leaderboard",
    "",
    renderPassAt1Chart(leaderboard),
    "",
    ]),
    "## Leaderboard",
    "",
    renderTable(leaderboard, [
      ["model", "Model"],
      ["config", "Config"],
      ["pass_at_1", "pass@1", formatPercent],
      ["pass_at_4", "pass@4", formatPercent],
      ["n_passed", "Passed"],
      ["n_attempted", "Attempts"],
      ["n_tasks_attempted", "Tasks"],
      ["median_cost_usd", "Median cost", formatUsd],
      ["median_steps", "Median steps"],
    ]),
    "",
    "See [the full generated data report](data/README.md) for comparisons, model behavior aggregates, verification behavior, critiques, corpus stats, repositories, and raw snapshot links.",
    "",
  ].join("\n");
}

type LeaderboardPoint = {
  label: string;
  passAt1: number;
  cost: number;
};

function renderEfficiencyChart(rows: Row[]): string {
  const points = getLeaderboardPoints(rows);
  if (points.length === 0) {
    return "_No chart data published._";
  }

  const maxCost = Math.max(...points.map((point) => point.cost));

  return [
    "```mermaid",
    "quadrantChart",
    "    title DeepSWE score vs average cost per task",
    "    x-axis Higher avg cost --> Lower avg cost",
    "    y-axis Lower pass at 1 --> Higher pass at 1",
    "    quadrant-1 Most efficient",
    "    quadrant-2 Higher score / higher cost",
    "    quadrant-3 Lower score / higher cost",
    "    quadrant-4 Lower score / lower cost",
    ...points.map((point) => `    ${toMermaidPointLabel(point.label)}: [${formatChartNumber(1 - point.cost / maxCost)}, ${formatChartNumber(point.passAt1)}]`),
    "```",
  ].join("\n");
}

function renderPassAt1Chart(rows: Row[]): string {
  const points = getLeaderboardPoints(rows);
  if (points.length === 0) {
    return "_No chart data published._";
  }

  const maxPercent = Math.max(80, Math.ceil(Math.max(...points.map((point) => point.passAt1 * 100)) / 10) * 10);

  return [
    "```mermaid",
    "xychart-beta",
    "    title \"DeepSWE pass@1 leaderboard\"",
    `    x-axis [${points.map((point) => `\"${escapeMermaidString(point.label)}\"`).join(", ")}]`,
    `    y-axis "pass at 1 (%)" 0 --> ${maxPercent}`,
    `    bar [${points.map((point) => (point.passAt1 * 100).toFixed(1)).join(", ")}]`,
    "```",
  ].join("\n");
}

function getLeaderboardPoints(rows: Row[]): LeaderboardPoint[] {
  return rows.flatMap((row) => {
    const model = typeof row.model === "string" ? row.model : null;
    const effort = typeof row.reasoning_efforts === "string" ? row.reasoning_efforts : null;
    const passAt1 = getNumber(row.pass_at_1);
    const cost = getNumber(row.median_cost_usd);
    if (!model || passAt1 === null || cost === null) {
      return [];
    }

    return [{ label: effort ? `${model} [${effort}]` : model, passAt1, cost }];
  });
}

function getNumber(value: JsonValue | undefined): number | null {
  return typeof value === "number" && Number.isFinite(value) ? value : null;
}

function toMermaidPointLabel(label: string): string {
  return label.replace(/[\[\]:,;]/g, "").replaceAll("]", "");
}

function escapeMermaidString(label: string): string {
  return label.replaceAll("\\", "\\\\").replaceAll("\"", "\\\"");
}

function formatChartNumber(value: number): string {
  return value.toFixed(3).replace(/0+$/, "").replace(/\.$/, "");
}

type Row = Record<string, JsonValue | undefined>;
type Column = [key: string, heading: string, formatter?: (value: JsonValue | undefined) => string];

function getArtifact(artifacts: Map<string, JsonObject>, name: string): JsonObject {
  const artifact = artifacts.get(name);
  if (!artifact) {
    throw new Error(`Missing artifact: ${name}`);
  }
  return artifact;
}

function getRows(artifact: JsonObject, key = "rows"): Row[] {
  const rows = artifact[key];
  return Array.isArray(rows) ? (rows as Row[]) : [];
}

function renderTable(rows: Row[], columns: Column[]): string {
  if (rows.length === 0) {
    return "_No rows published._";
  }

  return [
    `| ${columns.map(([, heading]) => heading).join(" | ")} |`,
    `| ${columns.map(() => "---").join(" | ")} |`,
    ...rows.map((row) => `| ${columns.map(([key, , formatter]) => escapeCell(formatter ? formatter(row[key]) : formatValue(row[key]))).join(" | ")} |`),
  ].join("\n");
}

function renderKeyValueTable(record: JsonObject): string {
  const entries = Object.entries(record);
  if (entries.length === 0) {
    return "_No values published._";
  }

  return [
    "| Metric | Value |",
    "| --- | --- |",
    ...entries.map(([key, value]) => `| ${escapeCell(key)} | ${escapeCell(formatValue(value))} |`),
  ].join("\n");
}

function renderCritiques(critiques: JsonObject): string {
  const headline = critiques.headline;
  const models = Array.isArray(critiques.models) ? (critiques.models as Row[]) : [];
  const headlineRows = headline && typeof headline === "object" && !Array.isArray(headline)
    ? Object.entries(headline).map(([dataset, stats]) => ({ dataset, ...(isRecord(stats) ? stats : {}) }))
    : [];
  const modelRows = models.map((row) => ({
    model: row.model,
    deepswe_bad_rate: getNestedNumber(row.deepswe, "bad_rate"),
    deepswe_fp_rate: getNestedNumber(row.deepswe, "fp_rate"),
    deepswe_fn_rate: getNestedNumber(row.deepswe, "fn_rate"),
    pro_bad_rate: getNestedNumber(row.pro, "bad_rate"),
    pro_fp_rate: getNestedNumber(row.pro, "fp_rate"),
    pro_fn_rate: getNestedNumber(row.pro, "fn_rate"),
  }));

  return [
    renderTable(headlineRows, [
      ["dataset", "Dataset"],
      ["n_reviewed", "Reviewed"],
      ["n_bad", "Bad"],
      ["bad_rate", "Bad rate", formatPercent],
      ["fp_rate", "False-positive rate", formatPercent],
      ["fn_rate", "False-negative rate", formatPercent],
    ]),
    "",
    renderTable(modelRows, [
      ["model", "Model"],
      ["deepswe_bad_rate", "DeepSWE bad rate", formatPercent],
      ["deepswe_fp_rate", "DeepSWE FP", formatPercent],
      ["deepswe_fn_rate", "DeepSWE FN", formatPercent],
      ["pro_bad_rate", "SWE-Bench Pro bad rate", formatPercent],
      ["pro_fp_rate", "SWE-Bench Pro FP", formatPercent],
      ["pro_fn_rate", "SWE-Bench Pro FN", formatPercent],
    ]),
  ].join("\n");
}

function isRecord(value: JsonValue | undefined): value is JsonObject {
  return Boolean(value && typeof value === "object" && !Array.isArray(value));
}

function getNestedNumber(value: JsonValue | undefined, key: string): number | null {
  if (!isRecord(value)) {
    return null;
  }
  const nested = value[key];
  return typeof nested === "number" ? nested : null;
}

function renderCorpusStats(corpusStats: JsonObject): string {
  const rows = ["deep_swe", "swebenchpro", "swebenchverified"].map((name) => {
    const stats = corpusStats[name];
    return {
      dataset: name,
      ...(stats && typeof stats === "object" && !Array.isArray(stats) ? stats : {}),
    };
  });

  return renderTable(rows, [
    ["dataset", "Dataset"],
    ["n_tasks", "Tasks"],
    ["prompt_chars_mean", "Mean prompt chars", formatNumber],
    ["prompt_chars_median", "Median prompt chars", formatNumber],
    ["patch_lines_mean", "Mean patch lines", formatNumber],
    ["patch_lines_median", "Median patch lines", formatNumber],
    ["patch_files_mean", "Mean patch files", formatNumber],
    ["patch_files_median", "Median patch files", formatNumber],
  ]);
}

function formatValue(value: JsonValue | undefined): string {
  if (value === undefined || value === null) {
    return "";
  }
  if (typeof value === "number") {
    return formatNumber(value);
  }
  if (typeof value === "boolean") {
    return value ? "true" : "false";
  }
  if (typeof value === "string") {
    return value;
  }
  return JSON.stringify(value);
}

function formatPercent(value: JsonValue | undefined): string {
  if (typeof value !== "number") {
    return formatValue(value);
  }
  return `${(value * 100).toFixed(1)}%`;
}

function formatUsd(value: JsonValue | undefined): string {
  if (typeof value !== "number") {
    return formatValue(value);
  }
  return `$${value.toFixed(2)}`;
}

function formatSeconds(value: JsonValue | undefined): string {
  if (typeof value !== "number") {
    return formatValue(value);
  }
  return `${formatNumber(value)}s`;
}

function formatNumber(value: JsonValue | undefined): string {
  if (typeof value !== "number") {
    return formatValue(value);
  }
  return Number.isInteger(value) ? value.toLocaleString("en-US") : value.toLocaleString("en-US", { maximumFractionDigits: 2 });
}

function escapeCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", "<br>");
}

await main();
